# Generated by Django 5.0.3 on 2024-04-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=512, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('contest_specs', models.TextField(max_length=16000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='maas.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Environment',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='environment', serialize=False, to='maas.team')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255, null=True)),
                ('ipv4_address', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
    ]
