# Generated by Django 5.0.3 on 2024-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='admin_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='judge_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
