# Generated by Django 5.0.3 on 2024-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0002_contest_admin_password_contest_judge_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='name',
        ),
        migrations.AddField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
