# Generated by Django 5.0.3 on 2024-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0003_rename_name_team_title_remove_contest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mooshak_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
