# Generated by Django 5.0.3 on 2024-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0004_team_mooshak_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
