# Generated by Django 5.0.3 on 2024-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0005_team_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_specs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
