# Generated by Django 5.0.3 on 2024-05-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0006_alter_contest_contest_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_environment',
            name='ipv4_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team_environment',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
