set         Type {}
set       Status ready
set        Fatal {}
set      Warning {}
set  Designation {}
set    Organizes {}
set        Email {}
set         Open 1714478400
set        Start {}
set         Stop {}
set        Close {}
set HideListings 100
set       Policy {}
set      Virtual {}
set     Register yes
set      Service {}
set  Incremental {}
set        Notes {}
set       groups {}
set    challenge problems
set  submissions {}
set    questions {}
set    printouts {}
set     balloons balloons
set    languages {}
set        users users
set     problems {}